/**
 * Firestore document shapes. Every document also has an `id` (the Firestore
 * doc id) once read on the client; it is not stored in the document body.
 *
 * Date-only fields (purchase dates, manufacturing dates…) are ISO strings
 * `YYYY-MM-DD`. Moments in time (createdAt, expiresAt…) are Firestore
 * Timestamps, typed loosely here so this package does not depend on a
 * Firebase SDK.
 */

export interface TimestampLike {
  toDate(): Date;
  toMillis(): number;
}

export type IsoDate = string;

export const ROLES = ['admin', 'manager', 'staff', 'technician'] as const;
export type Role = (typeof ROLES)[number];

export const GEAR_STATUSES = ['active', 'has_issues', 'quarantined', 'retired'] as const;
export type GearStatus = (typeof GEAR_STATUSES)[number];

/** What failing an inspection item does to the gear's status. */
export const FAILURE_OUTCOMES = ['note', 'has_issues', 'quarantined'] as const;
export type FailureOutcome = (typeof FAILURE_OUTCOMES)[number];

export type StatusChangeSource = 'manual' | 'created' | 'import' | 'inspection' | 'work_order' | 'issue';

export interface Link {
  label: string;
  url: string;
}

interface Stamped {
  createdAt?: TimestampLike;
  createdBy?: string;
  updatedAt?: TimestampLike;
  updatedBy?: string;
}

export interface WithId {
  id: string;
}

export interface UserProfile extends Stamped {
  email: string;
  displayName: string;
  role: Role;
  active: boolean;
  /** Access ends at this moment; null for permanent staff. */
  expiresAt: TimestampLike | null;
  phone?: string;
  slackUserId?: string;
  homeProgramAreaId?: string | null;
  lastSignInAt?: TimestampLike;
}

/** Keyed by lower-cased email. Consumed by the activateAccount function. */
export interface Invite extends Stamped {
  email: string;
  displayName?: string;
  role: Role;
  expiresAt: TimestampLike | null;
  homeProgramAreaId?: string | null;
}

export interface ProgramArea extends Stamped {
  name: string;
  description?: string;
  color?: string;
  active: boolean;
}

export interface Location extends Stamped {
  name: string;
  description?: string;
  parentId?: string | null;
  active: boolean;
}

export interface Category extends Stamped {
  name: string;
  description?: string;
  active: boolean;
}

export interface Manufacturer extends Stamped {
  name: string;
  website?: string;
  notes?: string;
  active: boolean;
}

/**
 * When a product's gear must be inspected with a given form. Due when either
 * limit is reached, whichever comes first. One schedule per form per product.
 */
export interface InspectionSchedule {
  formId: string;
  everyMonths?: number | null;
  everyDaysUsed?: number | null;
  /** Show as "due soon" (and remind) this many days ahead. Default 14. */
  reminderLeadDays?: number | null;
  /** Phase 4: require this inspection before each check-out. */
  beforeEachCheckout?: boolean;
}

/** A specific make and model (and optional variant) that we may own several of. */
export interface Product extends Stamped {
  manufacturerId: string | null;
  model: string;
  /** Size, length, color… e.g. "13 ft, blue". */
  variant?: string;
  categoryId: string | null;
  lifetimeYears?: number | null;
  replacementCost?: number | null;
  standards?: string;
  isPpe?: boolean;
  notes?: string;
  links?: Link[];
  inspectionSchedules?: InspectionSchedule[];
  active: boolean;
}

/** An individual piece of gear, e.g. "Raft 1". */
export interface Gear extends Stamped {
  name: string;
  productId: string | null;
  programAreaId: string | null;
  locationId: string | null;
  status: GearStatus;
  /** Why the status last changed — required whenever status changes. */
  statusReason?: string;
  statusSource?: StatusChangeSource;
  /** Upper-case code printed in the QR label (or on a pre-printed tag). */
  qrCode: string;
  serialNumber?: string;
  tags?: string[];
  mfgDate?: IsoDate | null;
  purchaseDate?: IsoDate | null;
  firstUseDate?: IsoDate | null;
  purchaseValue?: number | null;
  supplier?: string;
  customEol?: IsoDate | null;
  notes?: string;
  links?: Link[];
  retiredDate?: IsoDate | null;
  retiredReason?: string;
  coverPhotoId?: string | null;
  /** Phase 3: the single open work order generated by inspections, if any. */
  openInspectionWorkOrderId?: string | null;
  /** Latest inspection per form id — maintained by Cloud Functions. */
  inspectionState?: Record<string, FormInspectionState>;
  /** Usage totals — maintained by Cloud Functions (phase 4 adds logging). */
  stats?: GearStats;
}

export interface FormInspectionState {
  lastDate: IsoDate;
  lastInspectionId: string;
  failedCount: number;
  /** stats.daysUsed when this inspection was done, for usage-based schedules. */
  daysUsedAtLast: number;
}

export interface GearStats {
  daysUsed?: number;
  uses?: number;
}

/** gear/{gearId}/statusHistory/{id} — written by Cloud Functions only. */
export interface StatusChange {
  from: GearStatus | null;
  to: GearStatus;
  reason: string;
  source: StatusChangeSource;
  by: string | null;
  at: TimestampLike;
}

/** qrCodes/{code} — reverse index that keeps QR codes unique. */
export interface QrCodeIndex {
  gearId: string;
}

export interface Photo extends Stamped {
  gearId: string | null;
  inspectionId?: string | null;
  /** The inspection item the photo documents, if any. */
  inspectionItemId?: string | null;
  workOrderId?: string | null;
  storagePath: string;
  thumbPath: string;
  caption?: string;
  width?: number;
  height?: number;
  /** False until the image bytes have reached Cloud Storage (offline queue). */
  uploaded: boolean;
  uploadedBy: string;
  takenAt?: TimestampLike;
}

export interface LabelSettings {
  templateId: string;
  /** Nudge the whole sheet, in inches, to calibrate a printer. */
  offsetX: number;
  offsetY: number;
}

export interface AppSettings {
  orgName: string;
  /** Anyone signing in with a verified Google account on these domains joins as staff. */
  autoJoinDomains: string[];
  /** Base URL encoded into QR labels, e.g. https://gear.calleva.org */
  qrBaseUrl: string;
  labels: LabelSettings;
}

export interface AuditEntry {
  collection: string;
  docId: string;
  action: 'create' | 'update' | 'delete';
  by: string | null;
  at: TimestampLike;
  changedFields: string[];
}

/* ------------------------------------------------------------ inspections */

export const INSPECTION_ITEM_TYPES = ['pass_fail', 'number', 'text'] as const;
export type InspectionItemType = (typeof INSPECTION_ITEM_TYPES)[number];

export interface InspectionItem {
  /** Stable id within the form, so history survives re-ordering and edits. */
  id: string;
  prompt: string;
  help?: string;
  type: InspectionItemType;
  /** What failing this item does to the gear. Text items never fail. */
  failureOutcome: FailureOutcome;
  required: boolean;
  /** Number items fail when the reading is outside min…max. */
  min?: number | null;
  max?: number | null;
  unit?: string;
}

export interface InspectionForm extends Stamped {
  name: string;
  description?: string;
  /** Bumped on every save; inspections record the version they used. */
  version: number;
  items: InspectionItem[];
  active: boolean;
}

export type ResponseResult = 'pass' | 'fail' | 'na';

/** One answered item, with the item copied in as it was at the time. */
export interface InspectionResponse {
  itemId: string;
  prompt: string;
  type: InspectionItemType;
  failureOutcome: FailureOutcome;
  result: ResponseResult;
  value?: number | string | null;
  unit?: string;
  comment?: string;
}

export interface InspectionOverride {
  status: GearStatus;
  reason: string;
}

export interface Inspection extends Stamped {
  gearId: string;
  productId: string | null;
  formId: string;
  formName: string;
  formVersion: number;
  /** Date the inspection was done (may be back-dated). */
  date: IsoDate;
  inspectorId: string;
  responses: InspectionResponse[];
  notes?: string;
  failedCount: number;
  /** Worst failure outcome among failed items, as a gear status. */
  calculatedStatus: GearStatus;
  override?: InspectionOverride | null;
  /** Filled in by the Cloud Function that applies the result. */
  statusBefore?: GearStatus | null;
  statusApplied?: GearStatus | null;
  /** The work order this inspection's failures were added to, if any. */
  workOrderId?: string | null;
  processedAt?: TimestampLike | null;
}

/** Who looks after inspections for gear matching a scope. Most specific wins. */
export const ASSIGNMENT_SCOPES = ['product', 'category', 'location', 'programArea'] as const;
export type AssignmentScope = (typeof ASSIGNMENT_SCOPES)[number];

export interface InspectionAssignment extends Stamped {
  scope: AssignmentScope;
  refId: string;
  userIds: string[];
}

/* ------------------------------------------------------------ work orders */

export const WORK_ORDER_STATUSES = ['open', 'in_progress', 'waiting_parts', 'done', 'cancelled'] as const;
export type WorkOrderStatus = (typeof WORK_ORDER_STATUSES)[number];
export const OPEN_WORK_ORDER_STATUSES: readonly WorkOrderStatus[] = ['open', 'in_progress', 'waiting_parts'];

export const PRIORITIES = ['low', 'normal', 'high', 'urgent'] as const;
export type Priority = (typeof PRIORITIES)[number];

/** inspection = generated by a failed inspection (one open per gear); issue = reported by staff; manual = created by a manager. */
export type WorkOrderSource = 'inspection' | 'issue' | 'manual';

export interface WorkOrder extends Stamped {
  /** Sequential number, assigned by a Cloud Function (WO-0001). */
  number?: number | null;
  gearId: string;
  productId: string | null;
  title: string;
  description?: string;
  source: WorkOrderSource;
  /** How serious the problem is; drives the gear's status while open. */
  severity: FailureOutcome;
  status: WorkOrderStatus;
  priority: Priority;
  assigneeId: string | null;
  dueDate: IsoDate | null;
  /** Inspections whose failures this work order covers. */
  inspectionIds?: string[];
  /** Ask the server to fill assignee/due/priority from the rules (issue reports). */
  autoAssign?: boolean;
  resolution?: string;
  cost?: number | null;
  laborHours?: number | null;
  closedAt?: TimestampLike | null;
  closedBy?: string | null;
  /** The gear status the server applied when this was closed. */
  gearStatusAfterClose?: GearStatus | null;
}

export type WorkOrderLogType = 'created' | 'inspection' | 'comment' | 'status' | 'assigned' | 'due' | 'severity';

/** workOrders/{id}/log/{entry} — comments from people, the rest from Cloud Functions. */
export interface WorkOrderLogEntry {
  type: WorkOrderLogType;
  text: string;
  by: string | null;
  at: TimestampLike;
  inspectionId?: string | null;
}

/** Admin-adjustable rule for auto-generated work orders; the first match (by order) wins. */
export interface WorkOrderRule extends Stamped {
  order: number;
  name: string;
  /** Null / missing fields match anything. */
  severity?: FailureOutcome | null;
  programAreaId?: string | null;
  categoryId?: string | null;
  locationId?: string | null;
  assigneeId: string | null;
  dueInDays: number | null;
  priority: Priority;
}
