/**
 * Firestore document shapes. Every document also has an `id` (the Firestore
 * doc id) once read on the client; it is not stored in the document body.
 *
 * Date-only fields (purchase dates, manufacturing dates…) are ISO strings
 * `YYYY-MM-DD`. Moments in time (createdAt, expiresAt…) are Firestore
 * Timestamps, typed loosely here so this package does not depend on a
 * Firebase SDK.
 */

export interface TimestampLike {
  toDate(): Date;
  toMillis(): number;
}

export type IsoDate = string;

export const ROLES = ['admin', 'manager', 'staff', 'technician'] as const;
export type Role = (typeof ROLES)[number];

export const GEAR_STATUSES = ['active', 'has_issues', 'quarantined', 'retired'] as const;
export type GearStatus = (typeof GEAR_STATUSES)[number];

/** What failing an inspection item does to the gear's status. */
export const FAILURE_OUTCOMES = ['note', 'has_issues', 'quarantined'] as const;
export type FailureOutcome = (typeof FAILURE_OUTCOMES)[number];

export type StatusChangeSource = 'manual' | 'created' | 'import' | 'inspection' | 'work_order' | 'issue';

export interface Link {
  label: string;
  url: string;
}

interface Stamped {
  createdAt?: TimestampLike;
  createdBy?: string;
  updatedAt?: TimestampLike;
  updatedBy?: string;
}

export interface WithId {
  id: string;
}

export interface UserProfile extends Stamped {
  email: string;
  displayName: string;
  role: Role;
  active: boolean;
  /** Access ends at this moment; null for permanent staff. */
  expiresAt: TimestampLike | null;
  phone?: string;
  slackUserId?: string;
  homeProgramAreaId?: string | null;
  lastSignInAt?: TimestampLike;
}

/** Keyed by lower-cased email. Consumed by the activateAccount function. */
export interface Invite extends Stamped {
  email: string;
  displayName?: string;
  role: Role;
  expiresAt: TimestampLike | null;
  homeProgramAreaId?: string | null;
}

export interface ProgramArea extends Stamped {
  name: string;
  description?: string;
  color?: string;
  active: boolean;
}

export interface Location extends Stamped {
  name: string;
  description?: string;
  parentId?: string | null;
  active: boolean;
}

export interface Category extends Stamped {
  name: string;
  description?: string;
  active: boolean;
}

export interface Manufacturer extends Stamped {
  name: string;
  website?: string;
  notes?: string;
  active: boolean;
}

/** Placeholder for phase 2 — schedules are edited on the product page. */
export interface InspectionSchedule {
  formId: string;
  everyMonths?: number | null;
  everyDaysUsed?: number | null;
  reminderLeadDays?: number | null;
  beforeEachCheckout?: boolean;
}

/** A specific make and model (and optional variant) that we may own several of. */
export interface Product extends Stamped {
  manufacturerId: string | null;
  model: string;
  /** Size, length, color… e.g. "13 ft, blue". */
  variant?: string;
  categoryId: string | null;
  lifetimeYears?: number | null;
  replacementCost?: number | null;
  standards?: string;
  isPpe?: boolean;
  notes?: string;
  links?: Link[];
  inspectionSchedules?: InspectionSchedule[];
  active: boolean;
}

/** An individual piece of gear, e.g. "Raft 1". */
export interface Gear extends Stamped {
  name: string;
  productId: string | null;
  programAreaId: string | null;
  locationId: string | null;
  status: GearStatus;
  /** Why the status last changed — required whenever status changes. */
  statusReason?: string;
  statusSource?: StatusChangeSource;
  /** Upper-case code printed in the QR label (or on a pre-printed tag). */
  qrCode: string;
  serialNumber?: string;
  tags?: string[];
  mfgDate?: IsoDate | null;
  purchaseDate?: IsoDate | null;
  firstUseDate?: IsoDate | null;
  purchaseValue?: number | null;
  supplier?: string;
  customEol?: IsoDate | null;
  notes?: string;
  links?: Link[];
  retiredDate?: IsoDate | null;
  retiredReason?: string;
  coverPhotoId?: string | null;
  /** Phase 3: the single open work order generated by inspections, if any. */
  openInspectionWorkOrderId?: string | null;
}

/** gear/{gearId}/statusHistory/{id} — written by Cloud Functions only. */
export interface StatusChange {
  from: GearStatus | null;
  to: GearStatus;
  reason: string;
  source: StatusChangeSource;
  by: string | null;
  at: TimestampLike;
}

/** qrCodes/{code} — reverse index that keeps QR codes unique. */
export interface QrCodeIndex {
  gearId: string;
}

export interface Photo extends Stamped {
  gearId: string | null;
  inspectionId?: string | null;
  workOrderId?: string | null;
  storagePath: string;
  thumbPath: string;
  caption?: string;
  width?: number;
  height?: number;
  /** False until the image bytes have reached Cloud Storage (offline queue). */
  uploaded: boolean;
  uploadedBy: string;
  takenAt?: TimestampLike;
}

export interface LabelSettings {
  templateId: string;
  /** Nudge the whole sheet, in inches, to calibrate a printer. */
  offsetX: number;
  offsetY: number;
}

export interface AppSettings {
  orgName: string;
  /** Anyone signing in with a verified Google account on these domains joins as staff. */
  autoJoinDomains: string[];
  /** Base URL encoded into QR labels, e.g. https://gear.calleva.org */
  qrBaseUrl: string;
  labels: LabelSettings;
}

export interface AuditEntry {
  collection: string;
  docId: string;
  action: 'create' | 'update' | 'delete';
  by: string | null;
  at: TimestampLike;
  changedFields: string[];
}
